services:
  php:
    restart: unless-stopped
    build:
      target: prod
    volumes: !override
      - ./.secrets/jwt:/var/www/app/config/jwt:ro
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    env_file:
      - .env.production.local

  php-scheduler:
    restart: unless-stopped
    build:
      target: prod
    volumes: !override
      - ./.secrets/jwt:/var/www/app/config/jwt:ro
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    env_file:
      - .env.production.local

  php-reports-worker:
    restart: unless-stopped
    build:
      target: prod
    volumes: !override
      - ./.secrets/jwt:/var/www/app/config/jwt:ro
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    env_file:
      - .env.production.local

  nginx:
    restart: unless-stopped
    image: pizdec-nginx:prod
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes: !reset [ ]
    ports: !reset [ ]

  db:
    restart: unless-stopped
    ports: !reset [ ]

  rabbitmq:
    restart: unless-stopped
    ports: !reset []

  redis:
    restart: unless-stopped
    ports: !reset []

  minio:
    restart: unless-stopped
    ports: !reset []
  frontend:
    restart: unless-stopped
    build:
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    ports: !override
      - "127.0.0.1:${FRONTEND_PORT}:80"
