services:
  php:
    build:
      target: prod
    volumes: !reset []

  php-scheduler:
    build:
      target: prod
    volumes: !reset []

  php-reports-worker:
    build:
      target: prod
    volumes: !reset []

  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    ports: []
