parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Aws\S3\S3Client:
        arguments:
            -
                version: 'latest'
                region: '%env(MINIO_REGION)%'
                endpoint: '%env(MINIO_ENDPOINT)%'
                use_path_style_endpoint: true
                credentials:
                    key: '%env(MINIO_ACCESS_KEY)%'
                    secret: '%env(MINIO_SECRET_KEY)%'

    App\:
        resource: '../src/'

when@test:
    services:
        Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
            alias: security.user_password_hasher
            public: true
