<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609003202 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE buyer_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, total INT NOT NULL, delivery_region VARCHAR(255) NOT NULL, delivery_city VARCHAR(255) NOT NULL, delivery_street VARCHAR(255) NOT NULL, delivery_house VARCHAR(50) NOT NULL, delivery_postal_code VARCHAR(20) NOT NULL, delivery_entrance VARCHAR(50) DEFAULT NULL, delivery_apartment VARCHAR(50) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_270143D7E3C61F9 ON buyer_order (owner_id)');
        $this->addSql('CREATE TABLE buyer_order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, product_name VARCHAR(255) NOT NULL, product_price INT NOT NULL, product_weight INT NOT NULL, product_category VARCHAR(255) NOT NULL, quantity INT NOT NULL, line_total INT NOT NULL, buyer_order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A233E32834591598 ON buyer_order_item (buyer_order_id)');
        $this->addSql('ALTER TABLE buyer_order ADD CONSTRAINT FK_270143D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE buyer_order_item ADD CONSTRAINT FK_A233E32834591598 FOREIGN KEY (buyer_order_id) REFERENCES buyer_order (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE buyer_order DROP CONSTRAINT FK_270143D7E3C61F9');
        $this->addSql('ALTER TABLE buyer_order_item DROP CONSTRAINT FK_A233E32834591598');
        $this->addSql('DROP TABLE buyer_order');
        $this->addSql('DROP TABLE buyer_order_item');
    }
}
