nelmio_api_doc:
    documentation:
        info:
            title: Pizza Shop API
            description: API интернет-магазина пиццы и напитков
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/api(?!/doc(?:\.json)?$)
